/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "PC.v:1.1-24.10" *)
module PC(in, load, clk, rst, en, out);
  (* src = "PC.v:12.2-22.5" *)
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  (* src = "PC.v:8.11-8.13" *)
  wire _017_;
  (* src = "PC.v:4.23-4.25" *)
  wire _018_;
  (* src = "PC.v:4.23-4.25" *)
  wire _019_;
  (* src = "PC.v:4.23-4.25" *)
  wire _020_;
  (* src = "PC.v:4.23-4.25" *)
  wire _021_;
  (* src = "PC.v:4.23-4.25" *)
  wire _022_;
  (* src = "PC.v:4.23-4.25" *)
  wire _023_;
  (* src = "PC.v:4.23-4.25" *)
  wire _024_;
  (* src = "PC.v:4.23-4.25" *)
  wire _025_;
  (* src = "PC.v:5.11-5.15" *)
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  (* src = "PC.v:9.28-9.31" *)
  wire _059_;
  (* src = "PC.v:9.28-9.31" *)
  wire _060_;
  (* src = "PC.v:9.28-9.31" *)
  wire _061_;
  (* src = "PC.v:9.28-9.31" *)
  wire _062_;
  (* src = "PC.v:9.28-9.31" *)
  wire _063_;
  (* src = "PC.v:9.28-9.31" *)
  wire _064_;
  (* src = "PC.v:9.28-9.31" *)
  wire _065_;
  (* src = "PC.v:9.28-9.31" *)
  wire _066_;
  (* src = "PC.v:7.11-7.14" *)
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire [7:0] _085_;
  (* force_downto = 32'd1 *)
  (* src = "PC.v:19.16-19.23|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "7" *)
  wire [31:0] _086_;
  (* force_downto = 32'd1 *)
  (* src = "PC.v:19.16-19.23|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _087_;
  (* force_downto = 32'd1 *)
  (* src = "PC.v:19.16-19.23|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "8" *)
  wire [31:0] _088_;
  (* src = "PC.v:19.16-19.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _089_;
  (* src = "PC.v:19.16-19.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _090_;
  (* src = "PC.v:6.11-6.14" *)
  input clk;
  wire clk;
  (* src = "PC.v:8.11-8.13" *)
  input en;
  wire en;
  (* src = "PC.v:4.23-4.25" *)
  input [7:0] in;
  wire [7:0] in;
  (* src = "PC.v:5.11-5.15" *)
  input load;
  wire load;
  (* src = "PC.v:9.28-9.31" *)
  output [7:0] out;
  wire [7:0] out;
  (* src = "PC.v:7.11-7.14" *)
  input rst;
  wire rst;
  sky130_fd_sc_hd__clkinv_1 _091_ (
    .A(_067_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _092_ (
    .A(_017_),
    .SLEEP(_026_),
    .X(_027_)
  );
  sky130_fd_sc_hd__clkinv_1 _093_ (
    .A(_027_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _094_ (
    .A(_060_),
    .B(_059_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand3_1 _095_ (
    .A(_061_),
    .B(_060_),
    .C(_059_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__and4_1 _096_ (
    .A(_062_),
    .B(_061_),
    .C(_060_),
    .D(_059_),
    .X(_031_)
  );
  sky130_fd_sc_hd__nand2_1 _097_ (
    .A(_063_),
    .B(_031_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand3_1 _098_ (
    .A(_064_),
    .B(_063_),
    .C(_031_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand4_1 _099_ (
    .A(_065_),
    .B(_064_),
    .C(_063_),
    .D(_031_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__xor2_1 _100_ (
    .A(_066_),
    .B(_034_),
    .X(_035_)
  );
  sky130_fd_sc_hd__nor2_1 _101_ (
    .A(_026_),
    .B(_017_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__a22oi_1 _102_ (
    .A1(_026_),
    .A2(_025_),
    .B1(_036_),
    .B2(_066_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__o21ai_0 _103_ (
    .A1(_028_),
    .A2(_035_),
    .B1(_037_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _104_ (
    .A(_026_),
    .B(_024_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__a31oi_1 _105_ (
    .A1(_064_),
    .A2(_063_),
    .A3(_031_),
    .B1(_065_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__a22oi_1 _106_ (
    .A1(_027_),
    .A2(_034_),
    .B1(_036_),
    .B2(_065_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__o21ai_0 _107_ (
    .A1(_039_),
    .A2(_040_),
    .B1(_038_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand2_1 _108_ (
    .A(_026_),
    .B(_023_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__a21oi_1 _109_ (
    .A1(_063_),
    .A2(_031_),
    .B1(_064_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__a22oi_1 _110_ (
    .A1(_027_),
    .A2(_033_),
    .B1(_036_),
    .B2(_064_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__o21ai_0 _111_ (
    .A1(_042_),
    .A2(_043_),
    .B1(_041_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nand2_1 _112_ (
    .A(_026_),
    .B(_022_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nor2_1 _113_ (
    .A(_063_),
    .B(_031_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__a22oi_1 _114_ (
    .A1(_027_),
    .A2(_032_),
    .B1(_036_),
    .B2(_063_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__o21ai_0 _115_ (
    .A1(_045_),
    .A2(_046_),
    .B1(_044_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _116_ (
    .A(_026_),
    .B(_021_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__a31oi_1 _117_ (
    .A1(_061_),
    .A2(_060_),
    .A3(_059_),
    .B1(_062_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _118_ (
    .A1_N(_028_),
    .A2_N(_031_),
    .B1(_036_),
    .B2(_062_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__o21ai_0 _119_ (
    .A1(_048_),
    .A2(_049_),
    .B1(_047_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _120_ (
    .A(_026_),
    .B(_020_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__a21oi_1 _121_ (
    .A1(_060_),
    .A2(_059_),
    .B1(_061_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__a22oi_1 _122_ (
    .A1(_027_),
    .A2(_030_),
    .B1(_036_),
    .B2(_061_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__o21ai_0 _123_ (
    .A1(_051_),
    .A2(_052_),
    .B1(_050_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand2_1 _124_ (
    .A(_026_),
    .B(_019_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor2_1 _125_ (
    .A(_060_),
    .B(_059_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__a22oi_1 _126_ (
    .A1(_027_),
    .A2(_029_),
    .B1(_036_),
    .B2(_060_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__o21ai_0 _127_ (
    .A1(_054_),
    .A2(_055_),
    .B1(_053_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nand2_1 _128_ (
    .A(_026_),
    .B(_018_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__o21ai_0 _129_ (
    .A1(_026_),
    .A2(_017_),
    .B1(_059_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__o21ai_0 _130_ (
    .A1(_059_),
    .A2(_027_),
    .B1(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand2_1 _131_ (
    .A(_056_),
    .B(_058_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _132_ (
    .A(_067_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _133_ (
    .A(_067_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _134_ (
    .A(_067_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _135_ (
    .A(_067_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _136_ (
    .A(_067_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__clkinv_1 _137_ (
    .A(_067_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__clkinv_1 _138_ (
    .A(_067_),
    .Y(_008_)
  );
  (* src = "PC.v:12.2-22.5" *)
  sky130_fd_sc_hd__dfrtp_1 _139_ (
    .CLK(clk),
    .D(_077_),
    .Q(out[0]),
    .RESET_B(_069_)
  );
  (* src = "PC.v:12.2-22.5" *)
  sky130_fd_sc_hd__dfrtp_1 _140_ (
    .CLK(clk),
    .D(_078_),
    .Q(out[1]),
    .RESET_B(_070_)
  );
  (* src = "PC.v:12.2-22.5" *)
  sky130_fd_sc_hd__dfrtp_1 _141_ (
    .CLK(clk),
    .D(_079_),
    .Q(out[2]),
    .RESET_B(_071_)
  );
  (* src = "PC.v:12.2-22.5" *)
  sky130_fd_sc_hd__dfrtp_1 _142_ (
    .CLK(clk),
    .D(_080_),
    .Q(out[3]),
    .RESET_B(_072_)
  );
  (* src = "PC.v:12.2-22.5" *)
  sky130_fd_sc_hd__dfrtp_1 _143_ (
    .CLK(clk),
    .D(_081_),
    .Q(out[4]),
    .RESET_B(_073_)
  );
  (* src = "PC.v:12.2-22.5" *)
  sky130_fd_sc_hd__dfrtp_1 _144_ (
    .CLK(clk),
    .D(_082_),
    .Q(out[5]),
    .RESET_B(_074_)
  );
  (* src = "PC.v:12.2-22.5" *)
  sky130_fd_sc_hd__dfrtp_1 _145_ (
    .CLK(clk),
    .D(_083_),
    .Q(out[6]),
    .RESET_B(_075_)
  );
  (* src = "PC.v:12.2-22.5" *)
  sky130_fd_sc_hd__dfrtp_1 _146_ (
    .CLK(clk),
    .D(_084_),
    .Q(out[7]),
    .RESET_B(_076_)
  );
  assign { _086_[31:8], _086_[0] } = { 24'h000000, out[0] };
  assign _087_[31:1] = { 24'h000000, out[7:1] };
  assign { _088_[31:8], _088_[0] } = { 23'h000000, _086_[7], _087_[0] };
  assign _066_ = out[7];
  assign _084_ = _016_;
  assign _065_ = out[6];
  assign _083_ = _015_;
  assign _064_ = out[5];
  assign _082_ = _014_;
  assign _063_ = out[4];
  assign _081_ = _013_;
  assign _062_ = out[3];
  assign _080_ = _012_;
  assign _061_ = out[2];
  assign _079_ = _011_;
  assign _060_ = out[1];
  assign _078_ = _010_;
  assign _059_ = out[0];
  assign _077_ = _009_;
  assign _067_ = rst;
  assign _069_ = _001_;
  assign _070_ = _002_;
  assign _071_ = _003_;
  assign _072_ = _004_;
  assign _073_ = _005_;
  assign _074_ = _006_;
  assign _075_ = _007_;
  assign _076_ = _008_;
  assign _026_ = load;
  assign _017_ = en;
  assign _018_ = in[0];
  assign _019_ = in[1];
  assign _020_ = in[2];
  assign _021_ = in[3];
  assign _022_ = in[4];
  assign _023_ = in[5];
  assign _024_ = in[6];
  assign _025_ = in[7];
endmodule
