/* Generated By Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "PC.v:1.1-23.10" *)
module PC(in, load, clk, rst, out);
  (* src = "PC.v:11.2-21.5" *)
  wire [7:0] _000_;
  (* src = "PC.v:11.2-21.5" *)
  wire _001_;
  (* src = "PC.v:11.2-21.5" *)
  wire _002_;
  (* src = "PC.v:11.2-21.5" *)
  wire _003_;
  (* src = "PC.v:11.2-21.5" *)
  wire _004_;
  (* src = "PC.v:11.2-21.5" *)
  wire _005_;
  (* src = "PC.v:11.2-21.5" *)
  wire _006_;
  (* src = "PC.v:11.2-21.5" *)
  wire _007_;
  (* src = "PC.v:11.2-21.5" *)
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  (* src = "PC.v:4.23-4.25" *)
  wire _017_;
  (* src = "PC.v:4.23-4.25" *)
  wire _018_;
  (* src = "PC.v:4.23-4.25" *)
  wire _019_;
  (* src = "PC.v:4.23-4.25" *)
  wire _020_;
  (* src = "PC.v:4.23-4.25" *)
  wire _021_;
  (* src = "PC.v:4.23-4.25" *)
  wire _022_;
  (* src = "PC.v:4.23-4.25" *)
  wire _023_;
  (* src = "PC.v:4.23-4.25" *)
  wire _024_;
  (* src = "PC.v:5.11-5.15" *)
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  (* src = "PC.v:8.28-8.31" *)
  wire _048_;
  (* src = "PC.v:8.28-8.31" *)
  wire _049_;
  (* src = "PC.v:8.28-8.31" *)
  wire _050_;
  (* src = "PC.v:8.28-8.31" *)
  wire _051_;
  (* src = "PC.v:8.28-8.31" *)
  wire _052_;
  (* src = "PC.v:8.28-8.31" *)
  wire _053_;
  (* src = "PC.v:8.28-8.31" *)
  wire _054_;
  (* src = "PC.v:8.28-8.31" *)
  wire _055_;
  (* src = "PC.v:7.11-7.14" *)
  wire _056_;
  wire [7:0] _057_;
  wire [31:0] _058_;
  wire [31:0] _059_;
  (* src = "PC.v:18.16-18.23" *)
  (* unused_bits = "8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  (* force_downto = 32'd1 *)
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:266.22-266.23" *)
  wire [7:0] _069_;
  (* force_downto = 32'd1 *)
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:277.21-277.23" *)
  wire [31:0] _070_;
  (* force_downto = 32'd1 *)
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:282.21-282.26" *)
  wire [31:0] _071_;
  (* force_downto = 32'd1 *)
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:268.22-268.23" *)
  wire [31:0] _072_;
  (* force_downto = 32'd1 *)
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [31:0] _073_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:272.12-272.14" *)
  wire _074_;
  (* force_downto = 32'd1 *)
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:282.28-282.33" *)
  wire [31:0] _075_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:272.8-272.10" *)
  wire _076_;
  (* force_downto = 32'd1 *)
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [31:0] _077_;
  (* force_downto = 32'd1 *)
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _078_;
  (* force_downto = 32'd1 *)
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [31:0] _079_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:215.8-215.10" *)
  wire _080_;
  (* force_downto = 32'd1 *)
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:218.21-218.23" *)
  wire [31:0] _081_;
  (* force_downto = 32'd1 *)
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire [31:0] _082_;
  (* force_downto = 32'd1 *)
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.20-214.21" *)
  wire [31:0] _083_;
  wire [1023:0] _084_;
  (* force_downto = 32'd1 *)
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:222.21-222.22" *)
  wire [31:0] _085_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:220.10-220.11" *)
  wire [31:0] _086_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:220.13-220.14" *)
  wire [31:0] _087_;
  (* force_downto = 32'd1 *)
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:222.18-222.19" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _088_;
  wire [31:0] _089_;
  wire [31:0] _090_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)
  wire [31:0] _091_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *)
  wire [31:0] _092_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:279.26-279.45" *)
  wire [31:0] _093_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)
  wire [31:0] _094_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)
  wire [32:0] _095_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:231.18-231.27" *)
  wire _096_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _097_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _098_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _099_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _100_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _101_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _102_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _103_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _104_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _105_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _106_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _107_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _108_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _109_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _110_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _111_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _112_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _113_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _114_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _115_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _116_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _117_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _118_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _119_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _120_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _121_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _122_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _123_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _124_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _125_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _126_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _127_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _128_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _129_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _130_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _131_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _132_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _133_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _134_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _135_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _136_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _137_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _138_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _139_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _140_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _141_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _142_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _143_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _144_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _145_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _146_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _147_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _148_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _149_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _150_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _151_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _152_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _153_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _154_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _155_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _156_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _157_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _158_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _159_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _160_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _161_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _162_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _163_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _164_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _165_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _166_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _167_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _168_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _169_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _170_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _171_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _172_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _173_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _174_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _175_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _176_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _177_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _178_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _179_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _180_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _181_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _182_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _183_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _184_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _185_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _186_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _187_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _188_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _189_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _190_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _191_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _192_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _193_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _194_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _195_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _196_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _197_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _198_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _199_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _200_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _201_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _202_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _203_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _204_;
  (* src = "PC.v:18.16-18.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _205_;
  (* src = "PC.v:6.11-6.14" *)
  input clk;
  wire clk;
  (* src = "PC.v:4.23-4.25" *)
  input [7:0] in;
  wire [7:0] in;
  (* src = "PC.v:5.11-5.15" *)
  input load;
  wire load;
  (* src = "PC.v:8.28-8.31" *)
  output [7:0] out;
  wire [7:0] out;
  (* src = "PC.v:7.11-7.14" *)
  input rst;
  wire rst;
  sky130_fd_sc_hd__clkinv_1 _206_ (
    .A(_056_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _207_ (
    .A(_023_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__and4_1 _208_ (
    .A(_051_),
    .B(_050_),
    .C(_049_),
    .D(_048_),
    .X(_027_)
  );
  sky130_fd_sc_hd__and2_0 _209_ (
    .A(_052_),
    .B(_027_),
    .X(_028_)
  );
  sky130_fd_sc_hd__a31o_1 _210_ (
    .A1(_053_),
    .A2(_052_),
    .A3(_027_),
    .B1(_054_),
    .X(_029_)
  );
  sky130_fd_sc_hd__nand4_1 _211_ (
    .A(_054_),
    .B(_053_),
    .C(_052_),
    .D(_027_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__a21oi_1 _212_ (
    .A1(_029_),
    .A2(_030_),
    .B1(_025_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__a21oi_1 _213_ (
    .A1(_026_),
    .A2(_025_),
    .B1(_031_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__a31oi_1 _214_ (
    .A1(_053_),
    .A2(_052_),
    .A3(_027_),
    .B1(_025_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__o21ai_0 _215_ (
    .A1(_053_),
    .A2(_028_),
    .B1(_032_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _216_ (
    .A(_025_),
    .B(_022_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nand2_1 _217_ (
    .A(_033_),
    .B(_034_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nor2_1 _218_ (
    .A(_052_),
    .B(_027_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _219_ (
    .A(_025_),
    .B(_021_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__o31ai_1 _220_ (
    .A1(_025_),
    .A2(_028_),
    .A3(_035_),
    .B1(_036_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__a31oi_1 _221_ (
    .A1(_050_),
    .A2(_049_),
    .A3(_048_),
    .B1(_051_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _222_ (
    .A(_025_),
    .B(_020_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__o31ai_1 _223_ (
    .A1(_025_),
    .A2(_027_),
    .A3(_037_),
    .B1(_038_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__a21oi_1 _224_ (
    .A1(_049_),
    .A2(_048_),
    .B1(_050_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__a31o_1 _225_ (
    .A1(_050_),
    .A2(_049_),
    .A3(_048_),
    .B1(_025_),
    .X(_040_)
  );
  sky130_fd_sc_hd__nand2_1 _226_ (
    .A(_025_),
    .B(_019_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__o21ai_0 _227_ (
    .A1(_039_),
    .A2(_040_),
    .B1(_041_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__a21oi_1 _228_ (
    .A1(_049_),
    .A2(_048_),
    .B1(_025_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__o21ai_0 _229_ (
    .A1(_049_),
    .A2(_048_),
    .B1(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_1 _230_ (
    .A(_025_),
    .B(_018_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _231_ (
    .A(_043_),
    .B(_044_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand2_1 _232_ (
    .A(_025_),
    .B(_017_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__o21ai_0 _233_ (
    .A1(_048_),
    .A2(_025_),
    .B1(_045_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__xor2_1 _234_ (
    .A(_055_),
    .B(_030_),
    .X(_046_)
  );
  sky130_fd_sc_hd__nand2_1 _235_ (
    .A(_025_),
    .B(_024_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__o21ai_0 _236_ (
    .A1(_025_),
    .A2(_046_),
    .B1(_047_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _237_ (
    .A(_056_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__clkinv_1 _238_ (
    .A(_056_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__clkinv_1 _239_ (
    .A(_056_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__clkinv_1 _240_ (
    .A(_056_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _241_ (
    .A(_056_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__clkinv_1 _242_ (
    .A(_056_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__clkinv_1 _243_ (
    .A(_056_),
    .Y(_016_)
  );
  (* src = "PC.v:11.2-21.5" *)
  sky130_fd_sc_hd__dfrtp_1 _244_ (
    .CLK(clk),
    .D(_000_[5]),
    .Q(out[5]),
    .RESET_B(_062_)
  );
  (* src = "PC.v:11.2-21.5" *)
  sky130_fd_sc_hd__dfrtp_1 _245_ (
    .CLK(clk),
    .D(_000_[6]),
    .Q(out[6]),
    .RESET_B(_061_)
  );
  (* src = "PC.v:11.2-21.5" *)
  sky130_fd_sc_hd__dfrtp_1 _246_ (
    .CLK(clk),
    .D(_000_[7]),
    .Q(out[7]),
    .RESET_B(_068_)
  );
  (* src = "PC.v:11.2-21.5" *)
  sky130_fd_sc_hd__dfrtp_1 _247_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(out[0]),
    .RESET_B(_067_)
  );
  (* src = "PC.v:11.2-21.5" *)
  sky130_fd_sc_hd__dfrtp_1 _248_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(out[1]),
    .RESET_B(_066_)
  );
  (* src = "PC.v:11.2-21.5" *)
  sky130_fd_sc_hd__dfrtp_1 _249_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(out[2]),
    .RESET_B(_065_)
  );
  (* src = "PC.v:11.2-21.5" *)
  sky130_fd_sc_hd__dfrtp_1 _250_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(out[3]),
    .RESET_B(_064_)
  );
  (* src = "PC.v:11.2-21.5" *)
  sky130_fd_sc_hd__dfrtp_1 _251_ (
    .CLK(clk),
    .D(_000_[4]),
    .Q(out[4]),
    .RESET_B(_063_)
  );
  assign _077_ = _090_;
  assign _078_ = _089_;
  assign _079_ = _060_;
  assign _072_ = 32'd1;
  assign _069_ = out;
  assign _070_ = _071_;
  assign _073_ = _093_;
  assign _089_ = _094_;
  assign _060_ = _095_[31:0];
  assign _081_ = _090_;
  assign _082_ = _091_;
  assign _083_ = _089_;
  assign _084_ = 1024'h000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000070726f633b206f7074202d66617374;
  assign _085_ = _090_;
  assign _088_[0] = _089_[0];
  assign _087_ = 32'd32;
  assign _086_ = 32'd0;
  assign _075_ = 32'd1;
  assign _071_ = { 24'h000000, out };
  assign _055_ = out[7];
  assign _054_ = out[6];
  assign _053_ = out[5];
  assign _052_ = out[4];
  assign _051_ = out[3];
  assign _050_ = out[2];
  assign _049_ = out[1];
  assign _048_ = out[0];
  assign _056_ = rst;
  assign _061_ = _009_;
  assign _062_ = _010_;
  assign _063_ = _011_;
  assign _064_ = _012_;
  assign _065_ = _013_;
  assign _066_ = _014_;
  assign _067_ = _015_;
  assign _023_ = in[6];
  assign _025_ = load;
  assign _000_[6] = _007_;
  assign _022_ = in[5];
  assign _000_[5] = _006_;
  assign _021_ = in[4];
  assign _000_[4] = _005_;
  assign _020_ = in[3];
  assign _000_[3] = _004_;
  assign _019_ = in[2];
  assign _000_[2] = _003_;
  assign _018_ = in[1];
  assign _000_[1] = _002_;
  assign _017_ = in[0];
  assign _000_[0] = _001_;
  assign _068_ = _016_;
  assign _024_ = in[7];
  assign _000_[7] = _008_;
endmodule
