/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "A_Register.v:1.1-26.10" *)
module A_Register(in, enableA, loadA, rst, clk, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* src = "A_Register.v:5.11-5.18" *)
  wire _16_;
  (* src = "A_Register.v:4.23-4.25" *)
  wire _17_;
  (* src = "A_Register.v:4.23-4.25" *)
  wire _18_;
  (* src = "A_Register.v:4.23-4.25" *)
  wire _19_;
  (* src = "A_Register.v:4.23-4.25" *)
  wire _20_;
  (* src = "A_Register.v:4.23-4.25" *)
  wire _21_;
  (* src = "A_Register.v:4.23-4.25" *)
  wire _22_;
  (* src = "A_Register.v:4.23-4.25" *)
  wire _23_;
  (* src = "A_Register.v:4.23-4.25" *)
  wire _24_;
  (* src = "A_Register.v:6.11-6.16" *)
  wire _25_;
  (* src = "A_Register.v:9.24-9.27" *)
  wire _26_;
  (* src = "A_Register.v:9.24-9.27" *)
  wire _27_;
  (* src = "A_Register.v:9.24-9.27" *)
  wire _28_;
  (* src = "A_Register.v:9.24-9.27" *)
  wire _29_;
  (* src = "A_Register.v:9.24-9.27" *)
  wire _30_;
  (* src = "A_Register.v:9.24-9.27" *)
  wire _31_;
  (* src = "A_Register.v:9.24-9.27" *)
  wire _32_;
  (* src = "A_Register.v:9.24-9.27" *)
  wire _33_;
  (* src = "A_Register.v:7.11-7.14" *)
  wire _34_;
  (* src = "A_Register.v:12.20-12.23" *)
  wire _35_;
  (* src = "A_Register.v:12.20-12.23" *)
  wire _36_;
  (* src = "A_Register.v:12.20-12.23" *)
  wire _37_;
  (* src = "A_Register.v:12.20-12.23" *)
  wire _38_;
  (* src = "A_Register.v:12.20-12.23" *)
  wire _39_;
  (* src = "A_Register.v:12.20-12.23" *)
  wire _40_;
  (* src = "A_Register.v:12.20-12.23" *)
  wire _41_;
  (* src = "A_Register.v:12.20-12.23" *)
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  (* src = "A_Register.v:8.11-8.14" *)
  input clk;
  wire clk;
  (* src = "A_Register.v:5.11-5.18" *)
  input enableA;
  wire enableA;
  (* src = "A_Register.v:4.23-4.25" *)
  input [7:0] in;
  wire [7:0] in;
  (* src = "A_Register.v:6.11-6.16" *)
  input loadA;
  wire loadA;
  (* src = "A_Register.v:9.24-9.27" *)
  output [7:0] out;
  wire [7:0] out;
  (* src = "A_Register.v:7.11-7.14" *)
  input rst;
  wire rst;
  (* src = "A_Register.v:12.20-12.23" *)
  wire [7:0] val;
  sky130_fd_sc_hd__clkinv_1 _59_ (
    .A(_34_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__mux2_1 _60_ (
    .A0(_42_),
    .A1(_24_),
    .S(_25_),
    .X(_15_)
  );
  sky130_fd_sc_hd__mux2_1 _61_ (
    .A0(_41_),
    .A1(_23_),
    .S(_25_),
    .X(_14_)
  );
  sky130_fd_sc_hd__mux2_1 _62_ (
    .A0(_40_),
    .A1(_22_),
    .S(_25_),
    .X(_13_)
  );
  sky130_fd_sc_hd__mux2_1 _63_ (
    .A0(_39_),
    .A1(_21_),
    .S(_25_),
    .X(_12_)
  );
  sky130_fd_sc_hd__mux2_1 _64_ (
    .A0(_38_),
    .A1(_20_),
    .S(_25_),
    .X(_11_)
  );
  sky130_fd_sc_hd__mux2_1 _65_ (
    .A0(_37_),
    .A1(_19_),
    .S(_25_),
    .X(_10_)
  );
  sky130_fd_sc_hd__mux2_1 _66_ (
    .A0(_36_),
    .A1(_18_),
    .S(_25_),
    .X(_09_)
  );
  sky130_fd_sc_hd__mux2_1 _67_ (
    .A0(_35_),
    .A1(_17_),
    .S(_25_),
    .X(_08_)
  );
  sky130_fd_sc_hd__and2_0 _68_ (
    .A(_35_),
    .B(_16_),
    .X(_26_)
  );
  sky130_fd_sc_hd__and2_0 _69_ (
    .A(_36_),
    .B(_16_),
    .X(_27_)
  );
  sky130_fd_sc_hd__and2_0 _70_ (
    .A(_37_),
    .B(_16_),
    .X(_28_)
  );
  sky130_fd_sc_hd__and2_0 _71_ (
    .A(_38_),
    .B(_16_),
    .X(_29_)
  );
  sky130_fd_sc_hd__and2_0 _72_ (
    .A(_39_),
    .B(_16_),
    .X(_30_)
  );
  sky130_fd_sc_hd__and2_0 _73_ (
    .A(_40_),
    .B(_16_),
    .X(_31_)
  );
  sky130_fd_sc_hd__and2_0 _74_ (
    .A(_41_),
    .B(_16_),
    .X(_32_)
  );
  sky130_fd_sc_hd__and2_0 _75_ (
    .A(_42_),
    .B(_16_),
    .X(_33_)
  );
  sky130_fd_sc_hd__clkinv_1 _76_ (
    .A(_34_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__clkinv_1 _77_ (
    .A(_34_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _78_ (
    .A(_34_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _79_ (
    .A(_34_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__clkinv_1 _80_ (
    .A(_34_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__clkinv_1 _81_ (
    .A(_34_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__clkinv_1 _82_ (
    .A(_34_),
    .Y(_07_)
  );
  (* src = "A_Register.v:14.3-22.6" *)
  sky130_fd_sc_hd__dfrtp_1 _83_ (
    .CLK(clk),
    .D(_51_),
    .Q(val[0]),
    .RESET_B(_43_)
  );
  (* src = "A_Register.v:14.3-22.6" *)
  sky130_fd_sc_hd__dfrtp_1 _84_ (
    .CLK(clk),
    .D(_52_),
    .Q(val[1]),
    .RESET_B(_44_)
  );
  (* src = "A_Register.v:14.3-22.6" *)
  sky130_fd_sc_hd__dfrtp_1 _85_ (
    .CLK(clk),
    .D(_53_),
    .Q(val[2]),
    .RESET_B(_45_)
  );
  (* src = "A_Register.v:14.3-22.6" *)
  sky130_fd_sc_hd__dfrtp_1 _86_ (
    .CLK(clk),
    .D(_54_),
    .Q(val[3]),
    .RESET_B(_46_)
  );
  (* src = "A_Register.v:14.3-22.6" *)
  sky130_fd_sc_hd__dfrtp_1 _87_ (
    .CLK(clk),
    .D(_55_),
    .Q(val[4]),
    .RESET_B(_47_)
  );
  (* src = "A_Register.v:14.3-22.6" *)
  sky130_fd_sc_hd__dfrtp_1 _88_ (
    .CLK(clk),
    .D(_56_),
    .Q(val[5]),
    .RESET_B(_48_)
  );
  (* src = "A_Register.v:14.3-22.6" *)
  sky130_fd_sc_hd__dfrtp_1 _89_ (
    .CLK(clk),
    .D(_57_),
    .Q(val[6]),
    .RESET_B(_49_)
  );
  (* src = "A_Register.v:14.3-22.6" *)
  sky130_fd_sc_hd__dfrtp_1 _90_ (
    .CLK(clk),
    .D(_58_),
    .Q(val[7]),
    .RESET_B(_50_)
  );
  assign _42_ = val[7];
  assign _24_ = in[7];
  assign _25_ = loadA;
  assign _58_ = _15_;
  assign _41_ = val[6];
  assign _23_ = in[6];
  assign _57_ = _14_;
  assign _40_ = val[5];
  assign _22_ = in[5];
  assign _56_ = _13_;
  assign _39_ = val[4];
  assign _21_ = in[4];
  assign _55_ = _12_;
  assign _38_ = val[3];
  assign _20_ = in[3];
  assign _54_ = _11_;
  assign _37_ = val[2];
  assign _19_ = in[2];
  assign _53_ = _10_;
  assign _36_ = val[1];
  assign _18_ = in[1];
  assign _52_ = _09_;
  assign _35_ = val[0];
  assign _17_ = in[0];
  assign _51_ = _08_;
  assign _34_ = rst;
  assign _43_ = _00_;
  assign _44_ = _01_;
  assign _45_ = _02_;
  assign _46_ = _03_;
  assign _47_ = _04_;
  assign _48_ = _05_;
  assign _49_ = _06_;
  assign _50_ = _07_;
  assign _16_ = enableA;
  assign out[0] = _26_;
  assign out[1] = _27_;
  assign out[2] = _28_;
  assign out[3] = _29_;
  assign out[4] = _30_;
  assign out[5] = _31_;
  assign out[6] = _32_;
  assign out[7] = _33_;
endmodule
